# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65e70dd877be32a00beaeed684f807ac81143d969ddc2fa5d91723b481fb4c2c924334f22e47d7c1962b8c97551694e25d3a118bd3022b16e21852b71c072105

test:
  secret_key_base: f2457fb23fe64c8a2ac03b3dadf18bf82f9fa007a9dc66fa1e8fce04d26f1fac61d297495612d90fbebce5aea8d24bd5ce44a46ba7eb2a5e3b2e50380d96f927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
